<a href="https://colab.research.google.com/github/natsakh/IAD/blob/main/Pr_5%5C5_1_PyTorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cpu')

Tensors


In [2]:
x = torch.tensor([[0, 0, 1],[0, 1, 1],[1, 0, 1]])
print(x)
print(x.shape)

tensor([[0, 0, 1],
        [0, 1, 1],
        [1, 0, 1]])
torch.Size([3, 3])


In [3]:
x[0][0] = 5
print(x)

tensor([[5, 0, 1],
        [0, 1, 1],
        [1, 0, 1]])


In [4]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [5]:
torch.ones(1, 2)

tensor([[1., 1.]])

In [6]:
torch.rand(1).item() # створює тензор з одним випадковим числом у [0, 1) і повертає його як (float)(float32)

0.7600141763687134

In [7]:
torch.rand(2, 2).max().item()

0.46674221754074097

In [8]:
x = torch.tensor([[1., 2.],[3., 4.]], dtype=torch.float32, device=device)
y = torch.ones_like(x)
z = x + 2*y  # broadcasting приклад
print("x:", x)
print("y:", y)
print("z:", z)
print("dtype:", z.dtype, "device:", z.device, "shape:", z.shape)

# Перетворення з/до NumPy
a = z.cpu().numpy()
b = torch.from_numpy(a).to(device)
a[:1,:1], b[:1,:1] # показує перший елемент із масиву NumPy (a) і поверненого тензора PyTorch (b)

x: tensor([[1., 2.],
        [3., 4.]])
y: tensor([[1., 1.],
        [1., 1.]])
z: tensor([[3., 4.],
        [5., 6.]])
dtype: torch.float32 device: cpu shape: torch.Size([2, 2])


(array([[3.]], dtype=float32), tensor([[3.]]))

In [9]:
x = torch.tensor([[1., 2.],[3., 4.]], dtype=torch.float32)
y = torch.ones_like(x)
z = x + 2*y  # broadcasting приклад
print("x:", x)
print("y:", y)
print("z:", z)
print("dtype:", z.dtype, "device:", z.device, "shape:", z.shape)

# Перетворення з/до NumPy
a = z.numpy()
b = torch.from_numpy(a)
a[:1,:1], b[:1,:1]

x: tensor([[1., 2.],
        [3., 4.]])
y: tensor([[1., 1.],
        [1., 1.]])
z: tensor([[3., 4.],
        [5., 6.]])
dtype: torch.float32 device: cpu shape: torch.Size([2, 2])


(array([[3.]], dtype=float32), tensor([[3.]]))

In [10]:
flat_tensor = torch.rand(784)
reshaped_tensor = flat_tensor.reshape(1, 28, 28)
c_tensor = reshaped_tensor.permute(1, 2, 0)
print(flat_tensor.shape)
print(reshaped_tensor.shape)
print(c_tensor.shape)

torch.Size([784])
torch.Size([1, 28, 28])
torch.Size([28, 28, 1])


Gradients

In [11]:
# %% Create a tensor
x = torch.tensor(1.0)
print("x =", x)

# %% Simple calculations
y = 2 * x + 5
print("y = 2 * x + 5 =", y)

# %% Automatic gradient calculation
print("requires_grad flag:", x.requires_grad)  # False by default

x = tensor(1.)
y = 2 * x + 5 = tensor(7.)
requires_grad flag: False


In [12]:
# Set requires_grad after creation
x.requires_grad_()
print("requires_grad now:", x.requires_grad)

requires_grad now: True


In [13]:
# створюємо тензор з requires_grad=True
x = torch.tensor(1.0, requires_grad=True)

# визначаємо функцію y = x^2 + 5
y = x**2 + 5

# обчислюємо похідну dy/dx
y.backward()

print("Значення y при x=1:", y.item())
print("Похідна dy/dx при x=1:", x.grad.item())

Значення y при x=1: 6.0
Похідна dy/dx при x=1: 2.0


In [14]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cpu')

Щоб перейти на GPU (Colab)  
Runtime → Change runtime type  

У вікні, що відкриється -> Hardware accelerator -> GPU(за замовчуванням там стоїть None → означає CPU)  

Save

Colab Free

Час сесії: зазвичай до 12 годин (після цього сесія відключається, навіть якщо ще є ресурс).

Ліміти використання: приблизно 20–30 годин GPU на тиждень